server:
  port: 8080
spring:
  application:
    name: "boggle-game-manager"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        show_sql: false
        format_sql: false
        generate_statistics: false
        cache:
          use_second_level_cache: false
#  kafka:
#    bootstrap-servers: ${KAFKA_HOST}
#    producer:
#      retries: 1
#      client-id: "boggle-game-manager"
  mvc:
    problemdetails:
      enabled: true

#kafka-topics:
#  rooms:
#    name: rooms
#    partitions: 2
#    replicas: 1
#    configs:
#      cleanup.policy: delete
#      retention.ms: 86400000 # 1 day
#      retention.bytes: 5368709120 # 5GB
#      segment.ms: 86400000 # 1 day
#      segment.bytes: 1073741824 # 1GB